Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.provision "shell", path: "bootstrap.sh", name: "bootstrap"
	config.vm.provision "shell", path: "setup.sh", name: "setup", run:"always"
	config.vm.provision "shell", path: "startServer.sh", name: "startServer", run:"always"

	config.vm.network :forwarded_port, guest: 8000, host: 8000
	
	config.vm.synced_folder "../", "/project"
end
